#!/bin/bash

# This is an scripts managing lxd container
#
# Copyright 2022 Valentin LEFEBVRE
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

local container_name=${1}
local ip_addr=$(get_container_ip ${container_name})

# start and enbale ssh service
case "$2" in
    $CONTAINER_DISTRO_SUSE)
        lxc exec ${container_name} -- systemctl start sshd
        lxc exec ${container_name} -- systemctl enable sshd
        ;;
    $CONTAINER_DISTRO_DEBIAN | $CONTAINER_DISTRO_UBUNTU)
        lxc exec ${container_name} -- systemctl start ssh
        lxc exec ${container_name} -- systemctl enable ssh
        ;;
    $CONTAINER_DISTRO_CENTOS | $CONTAINER_DISTRO_FEDORA)
        lxc exec ${container_name} -- systemctl start sshd
        lxc exec ${container_name} -- systemctl enable sshd
        ;;
    *)
        echo_error "Unknown distro to start ssh services"
        ;;
esac

# If devel created add the ssh entry
if lxc exec ${container_name} -- id "devel" &>/dev/null; then
    if ! grep -Fxq "Host ${container_name}" ~/.ssh/config; then
        echo -e "" >> ${HOME}/.ssh/config
        echo -e "# generated by $0 - $1" >> ${HOME}/.ssh/config
        echo -e "Host ${container_name}" >> ${HOME}/.ssh/config
        echo -e "\tUser devel" >> ${HOME}/.ssh/config
        echo -e "\tHostname ${ip_addr}" >> ${HOME}/.ssh/config
        echo -e "\tPort 22" >> ${HOME}/.ssh/config
        echo -e "\tIdentityFile ~/.ssh/id_rsa" >> ${HOME}/.ssh/config
        
        lxc exec ${container_name} -- mkdir /home/devel/.ssh
        lxc file push ${HOME}/.ssh/id_rsa ${container_name}/home/devel/.ssh/
        lxc file push ${HOME}/.ssh/id_rsa.pub ${container_name}/home/devel/.ssh/

        sshpass -p "devel" ssh-copy-id -o StrictHostKeyChecking=no ${container_name}
    else 
        echo_info "Entry ssh for container ${container_name} already exists"
    fi
else 
    echo_info "No devel user created"
fi